# Site settings
title: Valentins Blog
email: valentin@sawadski.eu
description: > # this means to ignore newlines until "baseurl:"
  This is about hacking, technological advances and how to seize the
  opportunity! All from an entrepreneurial angle and based on personal
  experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _vsaw
github_username:  vsaw
exclude: ["Vagrantfile", "Vagrant", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: redcarpet

# GitHub Page Settings
highlighter: pygments
safe: true
lsi: false
