# Site settings
title: Valentin Sawadski
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
author:
    twitter: _vsaw
    github: vsaw
    bio: >
      This is about hacking, technological advances and how to seize the
      opportunity! All from an entrepreneurial angle and based on personal
      experiences.
    email_md5: 852b85aa04b05cb283891c04b7821a44

# Layout dbyll
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: "projects"
            type: "pages"
        values:
            layout: "project"
permalink: /blog/:year/:month/:title/
rss_path: blog/feed.xml
categories_path: blog/categories.html
tags_path: blog/tags.html
about_path: about/
projects_path: projects/
paginate: 10
paginate_path: "blog/page:num"

# Build settings
markdown: redcarpet

# GitHub Page Settings
highlighter: pygments
safe: true
lsi: false

# Local Environment Cleanup
exclude: ["Vagrantfile", "Vagrant", "Gemfile", "Gemfile.lock"]
